### ISSUE TITLE
Fix a warning in the unit tests

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#91]
This one, yeah:

```
PASS src/lib/widgets/podcasts/ui/specs/podcast-list.spec.ts
  ✓ renders all podcasts (14 ms)

  console.warn
    <Component> was created with unknown prop 'class'

       8 |   const sampleName = 'do stuff';
       9 |
    > 10 |   const sampleIcon = svelte`<div />`;
         |                   ^
      11 |   const iconButtonWithName = useLocalVars(
      12 |     svelte`<IconButton icon={sampleIcon} name={sampleName} />`,
      13 |     [IconButton, sampleIcon, sampleName]

      at src/lib/shared/ui/specs/icon-button.spec.ts:10:19
          at Array.forEach (<anonymous>)
      at instance (src/lib/shared/ui/specs/icon-button.spec.ts:10:19)
      at init (node_modules/.pnpm/svelte@3.46.4/node_modules/svelte/internal/index.js:1865:11)
      at new Component (src/lib/shared/ui/specs/icon-button.spec.ts:10:19)
      at Array.create_else_block (src/lib/shared/ui/icon-button.svelte:28:21)
      at create_fragment (src/lib/shared/ui/icon-button.svelte:272:94)
```

**Comment by illright** [comment]
Closed in #93
